checkpoint-restore/go-criu

- Makefile
`killall` fails to detect the `piggie` process after restore.
```sh
$ sudo -E make
[...]
Do restore
SUCCESS!
killall -9 piggie || :
piggie: no process found
$ pidof piggie
20702 20640
$ sudo killall -9 piggie
piggie: no process found
```
Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>
> make: Replace killall with pkill

- README.md
This PR adds `How to contribute` section to the README.md file.
The contributor guidelines are based on [CONTRIBUTING.md](https://github.com/containers/image/blob/master/CONTRIBUTING.md#submitting-pull-requests) from [containers/image](https://github.com/containers/image).
Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>
> make: Add contribution guidelines

- .travis.yml
Travis updated to run against go version 1.14.x and 1.13.x
> travis updated to run against go 1.14.x and 1.13.x

- README.md
To be able to be used as a Go module this switches go-criu to Semantic Versioning.
Starting with release 4.0.0 go-criu is tracking CRIU 3.14.
Once this is merged I would add the 4.0.0 tag.
> Prepare 4.0.0 release

- .travis.yml
- Makefile
- main.go
Using runc with '--criu /path/to/criu' fails with
msg="CRIU version check failed: exec: \"criu\": executable file not found in $PATH"
This adds SetCriuPath() to go-criu to allow runc to pass the location of the CRIU binary down to go-criu.
> Support a CRIU binary outside of the default PATH

- crit-go/magic-gen/go.mod
- crit-go/magic-gen/go.sum
Add a separate go.mod to crit-go/magic-gen since it's a separate
binary which is not part of the library/package.
Generated by:
```
cd crit-go/magic-gen
touch go.mod
go mod tidy
```
> Fix go.mod

- phaul/client.go
I noticed that ```iter``` was initialized to zero but never incremented in the migration loop which caused an infinite loop when migrating.
I was doing some changes to criu source relating to pre-dumps and testing my changes using ```make phaul-test``` to see how it would affect migration.
I left only this check https://github.com/checkpoint-restore/go-criu/blob/89311a427477b4de836765a76833a80616085d19/phaul/client.go#L34 in the ```isLastIter``` check just for testing purposes forcing at least ```maxIters``` iterations. That's when I discovered the problem that ```iter``` was never incremented in the migration causing an infinite number of iterations.
> phaul: fix infinite pre-dump iterations in Migrate()

- .github/workflows/main.yml
Go 1.13.x is not supported since go 1.15 was released in August 2020.
Go 1.16 will be released this month, it makes sense to try it now.
> gha: add go 1.16-rc1, rm 1.13.x

- test/piggie.c
When `make` is run by non-root, we get a funny test failure:
> test/piggie
> Child forked, pid -1
> test/test dump `pidof piggie` image
> CRIU version 31500
> panic: runtime error: index out of range [3] with length 3
>
> goroutine 1 [running]:
> main.main()
>         /home/kir/go/src/github.com/checkpoint-restore/go-criu/test/main.go:80 +0xd0f
> make: *** [Makefile:28: test] Error 2
After this commit it's a bit more clear/correct:
> test/piggie
> clone() failed: Operation not permitted
> make: *** [Makefile:27: test] Error 1
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
> test/piggie.c: handle error from clone()

- .github/workflows/main.yml
As the final go 1.16 is released, rc1 is no longer available.
This fixes our CI.
> ci/gha: bump go 1.16-rc1 -> 1.16.x

- README.md
In anticipation of v5.0.0 release, add some info to README (and fix some nits while at it).
- README: no links in header, highlight go code
- README: provide a complete example that includes import statement
- README: add info about v5, use a table
- README: add link to go doc
> README: prepare for v5.0.0

- Makefile
- features.go
- main.go
- test/main.go
This adds the feature checking interface with the same semantics as the feature checking through libcriu.
> Add feature checking support to go-criu

- .github/workflows/main.yml
The `--depth=1` option of `git clone` would reduce the amount of downloaded data by creating a shallow clone of the CRIU repository. The `--jobs` option tells `make` to use parallelism when building CRIU.
> ci: optimize build

- .github/workflows/main.yml
- Makefile
- test/Makefile
Running tests with CRIU requires root privileges, however, building go binaries does not. This patch separates the build steps from the steps used to run tests. This allows to build applications such as crit using `make` without root privileges.
> Add makefile for testing

- .github/workflows/main.yml
- test/Makefile
The current [default target](https://www.gnu.org/software/make/manual/html_node/Rules.html) in test/Makefile is `test-bin` as this is the first target in the makefile. This was unintentional change introduced in https://github.com/checkpoint-restore/go-criu/pull/71. The default target should be `all`. However, `test-bin` does not appear to be used anywhere and thus, we can remove it.
> test: drop test-bin target

- crit/cmd/cli.go
- crit/crit.go
The crit CLI app now supports reading input from stdin. Input can also
be sent through a pipe or I/O redirection.
Signed-off-by: Prajwal S N <prajwalnadig21@gmail.com>
> fix(crit): read from stdin in CLI app

- test/Makefile
In commit 958702777582dab243bf68e949e49218ee1b1aff the `test.coverage` command was moved into a Makefile located in the `test/` subdirectory.
> test: fix running test.coverage command

- go.mod
- vendor/modules.txt
1.16 ensures that we retain compatibility with Podman.
> chore: bump Go version to 1.16

- .github/workflows/main.yml
- phaul/api.go
- phaul/server.go
- rpc/rpc.pb.go
- test/main_coverage_test.go
The verify / lint CI workflow running `golangci-lint` currently fails with:
```
phaul/api.go:30: File is not `gofmt`-ed with `-s` (gofmt)
//Methods:
phaul/server.go:37: File is not `gofmt`-ed with `-s` (gofmt)
//
```
This problem has been reported in https://github.com/golangci/golangci-lint-action/issues/535
The problem occurs because, for some reason, golangci-lint is using `gofmt` from go 1.19. This pull request formats the code using gofmt and enables the CI tests to run with go 1.19.
> ci: enable tests with go 1.19.x

- crit/explore.go
- crit/stats.go
- crit/utils.go
- test/crit/Makefile
- test/crit/stats_test.go
This also fixes some of the places where `fmt.Sprintf` was being used instead of `filepath.Join`
> Add functions for stats

- .golangci.yml
The musttag checker exits with status code 1 and kills the linter pipeline. Since nothing else is logged, disabling it seems to be the only fix for now. Running golangci-lint locally does not cause this issue, so it looks like a problem with the specific version of `musttag` that's being used in the GitHub action. I'll ping the golangci folks and let them know about this.
> ci: disable musttag in golangci-lint

- .github/workflows/verify.yml
- README.md
This introduces a markdown linter for the go-criu repo. It runs only if a PR modifies any of the README.md files present. The commit also fixes the initial issues raised on the top-level readme.
cc @adrianreber
> ci: add markdown linter

- .gitignore
- test/Makefile
This pull request extends the code coverage to include the integration tests for `crit`.
> Enable coverage for crit-test

- .golangci.yml
- test/main.go
This PR mainly fixes a crash when the feature check environment variables were not set.
I included another commit that fixes a complaint from `staticcheck` and enabled in a third commit additional CI checks.
> Fix crash when feature check environment variables are not set

- .github/workflows/main.yml
The CI job that installed protoc-gen-go was using a deprecated package path. It has been updated with the path to the active package path.
cc @rst0git
> ci: fix protoc-gen-go path for go install

- .github/workflows/main.yml
- .gitignore
- crit/Makefile
- crit/stats_test.go
- test/Makefile
- test/crit/Makefile
- test/loop/Makefile
This pull request enables code coverage for CRIT's [unit](https://go.dev/blog/cover) and [e2e](https://go.dev/testing/coverage/) tests.
> test: enable coverage of crit unit/e2e tests

- .github/workflows/main.yml
This pull request adds a concurrency group to the main CI workflow to automatically cancel any in-progress workflows when a pull request has been updated.
This [concurrency group](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) ensures that a single workflow will run at a time. For example, when a pull request is updated with a force-push, the GiHub CI workflows currently in-progress will be automatically cancelled, and the CI would run only with the updated commits.
An exception is used for the 'master' branch, so that when multiple pull requests have been merged, the CI would run for each merge commit.
> ci: cancel preceding workflows run

- crit/mempages.go
- crit/mempages_test.go
- test/crit/Makefile
- test/crit/main.go
The goal of this PR is to add features for collecting memory pages content. 
For the now I have added `GetMemPages` function to retrieve the memory pages of a process. Alongside it, helper functions `genMemChunk` and `getPage` have been implemented. The core logic is derived from https://github.com/checkpoint-restore/criu/blob/criu-dev/coredump/criu_coredump/coredump.py. 
It's still a work in progress, but I would like to submit it for feedback. 
PTAL: @adrianreber, @rst0git 
Thank you!
> crit: add features to retrieve memory pages

- crit/explore.go
- crit/utils.go
This would be useful for us to extend the info displayed by checkpointctl. Since we're anyway holding the information with us in the object, we might as well just provide that information too.
> feat(crit): add type to file descriptor

- MAINTAINERS
This pull request adds Prajwal S N (@snprajwal) as a maintainer to the go-criu repository. He has contributed a significant amount of code and has been helping with maintaining it.
> Add Prajwal S N as a maintainer

- crit/Makefile
Previously, the Makefile in `crit` would not rebuild the binary even if any of the related source files changed. This is now fixed by marking all Go files under the directory as prerequisites for the `bin/crit` recipe.
> chore(crit): improve Makefile rule

- crit/mempages.go
This commit introduces a getter function that allows accessing the value of the `pagesID` field within the `MemoryReader` struct. This function will be beneficial for enabling `checkpointctl` to extract only the required page image files efficiently.
> crit: add getter for `pagesID` field in `MemoryReader` struct

- crit/utils.go
- crit/utils_test.go
This commit introduces a new method `FindPs` on `PsTree`. This method uses a depth-first search algorithm to find a process within a process tree. This addition will be beneficial for `checkpointctl` as it allows us to easily verify the existence of a given process ID when needed.
> crit: add `FindPs` method on `PsTree`

- crit/cli/cli.go
- crit/crit.go
- crit/explore.go
- crit/utils.go
- crit/utils_test.go
- test/crit/crit-test.sh
- test/loop/loop.c
This is useful for implementing socket views in checkpointctl, going forward.
> feat(crit): add `crit x sk` for sockets

- crit/explore.go
- crit/mempages.go
- main.go
- test/main.go
The new version of golangci-lint enables a new linter, which checks for direct access to protobuf fields. The offending instances have now been fixed.
> chore: fix lints from `protogetter`

- crit/image.go
Previously, the JSON output generated through `protojson.Marshal` was using camelCased names for the keys. It now uses snake_case, which is consistent with the behaviour of the Python implementation of CRIT.
Closes #154
cc @rst0git
> fix(crit): use proto names in JSON

- crit/decode-extra.go
- crit/explore.go
Missed this the last time, this just prevents inconsistency across the different commands. Related to #154
> fix(crit): use snake_case names in `crit explore`

- codecov.yml
Codecov ignores unit tests by default, but does not recognise the `test` directory for integration tests. Tests are written to generate coverage, so it does not make sense to check the coverage of the tests themselves.
> fix(coverage): ignore test files

- test/main.go
- utils/criu.go
- utils/criu_linux.go
- utils/criu_unsupported.go
Convenience functions to check if CRIU is available and at least a certain version are now used in containerd, CRI-O and Podman. This change moves those functions to go-criu.
I am not entirely sure about the naming and the location. If this used somewhere else it would be:
```
import "github.com/checkpoint-restore/go-criu/v7/utils"
...
utils.GetCriuVersion()
```
Which results in `utils`, which is a very generic name. Maybe changing the directory name to `crutils` would be better?
```
import "github.com/checkpoint-restore/go-criu/v7/crutils"
...
crutils.GetCriuVersion()
```
Not sure. Any ideas about naming to make it easy to include and understand where it is coming from?
> Add functions which are used in Podman, CRI-O and containerd

- README.md
Just bumps the README before tagging the release. Closes #167
> release: v7.1.0

- .github/workflows/main.yml
- go.mod
This pull request updates the minimum go version to 1.20. These changes are required for https://github.com/checkpoint-restore/go-criu/pull/175
> go.mod: bump Go version to 1.20

- main.go
- phaul/client.go
- test/main.go
In the podman CI we are seeing a weird flake during criu version detection[1]. The write to the socket just fails with broken pipe. The logical thing to assume here is that the child exited. However the current code never reports back the child error from wait nor does it try to capture the output from it. This fixes both. The cleanup error is now added to the returned error so the caller sees both.
As errors.Join is used from the std lib bump the minimum go version to 1.20.
[1] https://github.com/containers/podman/issues/18856
> criu swrk: return child error to caller

- .github/workflows/codecov.yml
`codecov-action@v4` requires an [organization-level upload token](https://docs.codecov.com/docs/codecov-uploader#upload-token) instead of a single repository upload token. Thus, uploading codecov report fails with the following error when triggered by the push event of a merged pull request:
Commit creating failed: {"detail":"You do not have permission to perform this action."}
We are temporarily downgrading from v4 to v3 until we can generate an organization-level upload token.
> ci: downgrade 'codecov-action' version to v3

- crit/mempages.go
- crit/mempages_test.go
- test/loop/loop.c
I am currently working on a feature to allow users to search for a pattern within process memory pages, as suggested by @rst0git last year. This could be used to extend `checkpointctl memparse` with search capability. 
Currently, the method `SearchPattern(pattern string) (uint64, error)` takes the pattern to search as an argument and returns the address of the first match along with an error if the pattern is not found. I am not sure about the implementation yet, and I'm considering alternative approaches:
- Instead of providing just the address of the first match, should we consider returning the entire memory pages where the pattern is found?
- Another consideration is whether to return not just the first match but all occurrences of the pattern.
@rst0git, @adrianreber , @snprajwal …
> feat(crit): add SearchPattern method on MemoryReader

- .golangci.yml
Changes were made to this check in v1.60.2, which introduced a lot of noise and false positives. This commit disables this for now.
Ref: https://github.com/securego/gosec/issues/1185
> ci(golangci-lint): disable gosec G115

- .github/workflows/main.yml
- crit/mempages.go
- crit/mempages_unix.go
- crit/mempages_windows.go
- crit/utils.go
- crit/utils_linux.go
- crit/utils_other.go
When using CRIT on macOS, the following errors occur:
```
../../../go/pkg/mod/github.com/checkpoint-restore/go-criu/v7@v7.2.0/crit/utils.go:329:15: undefined: syscall.AF_NETLINK
../../../go/pkg/mod/github.com/checkpoint-restore/go-criu/v7@v7.2.0/crit/utils.go:331:15: undefined: syscall.AF_BRIDGE
../../../go/pkg/mod/github.com/checkpoint-restore/go-criu/v7@v7.2.0/crit/utils.go:333:15: undefined: syscall.AF_KEY
../../../go/pkg/mod/github.com/checkpoint-restore/go-criu/v7@v7.2.0/crit/utils.go:335:15: undefined: syscall.AF_PACKET
../../../go/pkg/mod/github.com/checkpoint-restore/go-criu/v7@v7.2.0/crit/utils.go:359:15: undefined: syscall.SOCK_PACKET
../../../go/pkg/mod/github.com/checkpoint-restore/go-criu/v7@v7.2.0/crit/utils.go:381:15: undefined: syscall.IPPROTO_UDPLITE
```
I believe that …
> add(crit): other os support

- .github/workflows/main.yml
- .github/workflows/verify.yml
The Go matrix is unnecessary, as Go provides backwards compatibility across existing APIs, and we are almost always just one version behind the latest one.
> ci: bump actions, remove Go matrix

- crit/explore.go
- crit/utils.go
Caching common criu images in global variables doesn't work in these scenarios:
- crit.Explore...() are used in different img directories
- between crit.Explore...() img files are updated (new dump happened)
With this PR I'm fixing this problem and supporting listed cases by invalidating the caches during each Explore call.
> Invalidate global vars containing parsed images in Explore* methods
